In [2]:
import pandas as pd 
matches = pd.read_csv("matches_laliga_2025_2026.csv" , index_col=0)
matches.head()

,time,comp,round,day,venue,result,gf,ga,opponent,sh,sot,fouls,corners,yellow,red,season,team
date,,,,,,,,,,,,,,,,,
2025-08-15,18:00,La Liga,Matchweek 1,Fri,Home,L,1,3,Vallecano,7,2,8,2,0,1,2025-2026,Girona
2025-08-15,18:00,La Liga,Matchweek 1,Fri,Away,W,3,1,Girona,16,5,17,4,1,0,2025-2026,Vallecano
2025-08-15,20:30,La Liga,Matchweek 1,Fri,Away,L,0,2,Villarreal,5,4,8,1,2,1,2025-2026,Oviedo
2025-08-15,20:30,La Liga,Matchweek 1,Fri,Home,W,2,0,Oviedo,25,10,10,10,1,0,2025-2026,Villarreal
2025-08-16,18:30,La Liga,Matchweek 1,Sat,Away,W,3,0,Mallorca,24,8,17,6,1,0,2025-2026,Barcelona

In [3]:
matches.shape

(760, 17)

In [8]:
matches["team"].value_counts()

team
Girona         38
Vallecano      38
Oviedo         38
Villarreal     38
Barcelona      38
Mallorca       38
Alaves         38
Levante        38
Sociedad       38
Valencia       38
Celta          38
Getafe         38
Ath Bilbao     38
Sevilla        38
Ath Madrid     38
Espanol        38
Betis          38
Elche          38
Osasuna        38
Real Madrid    38
Name: count, dtype: int64

In [9]:
38 * 20 * 2

1520

In [10]:
matches[matches["team"] == "Real Madrid"]

,time,comp,round,day,venue,result,gf,ga,opponent,sh,sot,fouls,corners,yellow,red,season,team
date,,,,,,,,,,,,,,,,,
2025-08-19,20:00,La Liga,Matchweek 1,Tue,Home,W,1,0,Osasuna,18,5,10,7,1,0,2025-2026,Real Madrid
2025-08-24,20:30,La Liga,Matchweek 2,Sun,Away,W,3,0,Oviedo,26,10,7,9,1,0,2025-2026,Real Madrid
2025-08-30,20:30,La Liga,Matchweek 3,Sat,Home,W,2,1,Mallorca,17,7,12,4,2,0,2025-2026,Real Madrid
2025-09-13,15:15,La Liga,Matchweek 4,Sat,Away,W,2,1,Sociedad,16,6,7,4,1,1,2025-2026,Real Madrid
2025-09-20,15:15,La Liga,Matchweek 5,Sat,Home,W,2,0,Espanol,16,5,10,5,2,0,2025-2026,Real Madrid
2025-09-23,20:30,La Liga,Matchweek 6,Tue,Away,W,4,1,Levante,24,10,9,7,1,0,2025-2026,Real Madrid
2025-09-27,15:15,La Liga,Matchweek 7,Sat,Away,L,2,5,Ath Madrid,6,2,14,2,4,0,2025-2026,Real Madrid
2025-10-04,20:00,La Liga,Matchweek 8,Sat,Home,W,3,1,Villarreal,26,7,9,4,2,0,2025-2026,Real Madrid
2025-10-19,20:00,La Liga,Matchweek 9,Sun,Away,W,1,0,Getafe,23,10,11,4,1,0,2025-2026,Real Madrid
2025-10-26,15:15,La Liga,Matchweek 10,Sun,Home,W,2,1,Barcelona,23,10,12,12,5,1,2025-2026,Real Madrid
2025-11-01,20:00,La Liga,Matchweek 11,Sat,Home,W,4,0,Valencia,21,11,14,7,1,0,2025-2026,Real Madrid
2025-11-09,15:15,La Liga,Matchweek 12,Sun,Away,D,0,0,Vallecano,21,5,7,8,2,0,2025-2026,Real Madrid
2025-11-23,20:00,La Liga,Matchweek 13,Sun,Away,D,2,2,Elche,20,7,8,8,0,0,2025-2026,Real Madrid
2025-11-30,20:00,La Liga,Matchweek 14,Sun,Away,D,1,1,Girona,25,4,13,5,0,0,2025-2026,Real Madrid
2025-12-03,18:00,La Liga,Matchweek 15,Wed,Away,W,3,0,Ath Bilbao,13,8,4,7,0,0,2025-2026,Real Madrid
2025-12-07,20:00,La Liga,Matchweek 16,Sun,Home,L,0,2,Celta,23,7,6,8,6,3,2025-2026,Real Madrid
2025-12-14,20:00,La Liga,Matchweek 17,Sun,Away,W,2,1,Alaves,13,6,13,7,1,0,2025-2026,Real Madrid
2025-12-20,20:00,La Liga,Matchweek 18,Sat,Home,W,2,0,Sevilla,18,8,13,6,2,0,2025-2026,Real Madrid
2026-01-04,15:15,La Liga,Matchweek 19,Sun,Home,W,5,1,Betis,19,9,10,5,1,0,2025-2026,Real Madrid
2026-01-17,13:00,La Liga,Matchweek 20,Sat,Home,W,2,0,Levante,26,11,12,8,2,0,2025-2026,Real Madrid
2026-01-24,20:00,La Liga,Matchweek 21,Sat,Away,W,2,0,Villarreal,14,4,10,6,1,0,2025-2026,Real Madrid
2026-02-01,13:00,La Liga,Matchweek 22,Sun,Home,W,2,1,Vallecano,16,6,6,9,2,0,2025-2026,Real Madrid
2026-02-08,20:00,La Liga,Matchweek 23,Sun,Away,W,2,0,Valencia,11,6,13,8,1,0,2025-2026,Real Madrid
2026-02-14,20:00,La Liga,Matchweek 24,Sat,Home,W,4,1,Sociedad,11,5,10,4,1,0,2025-2026,Real Madrid
2026-02-21,17:30,La Liga,Matchweek 25,Sat,Away,L,1,2,Osasuna,15,5,10,7,4,0,2025-2026,Real Madrid
2026-03-02,20:00,La Liga,Matchweek 26,Mon,Home,L,0,1,Getafe,18,7,11,10,4,1,2025-2026,Real Madrid
2026-03-06,20:00,La Liga,Matchweek 27,Fri,Away,W,2,1,Celta,14,3,12,6,2,0,2025-2026,Real Madrid
2026-03-14,20:00,La Liga,Matchweek 28,Sat,Home,W,4,1,Elche,14,6,11,5,1,0,2025-2026,Real Madrid
2026-03-22,20:00,La Liga,Matchweek 29,Sun,Home,W,3,2,Ath Madrid,17,10,2,4,1,1,2025-2026,Real Madrid
2026-04-04,15:15,La Liga,Matchweek 30,Sat,Away,L,1,2,Mallorca,15,6,13,4,2,0,2025-2026,Real Madrid
2026-04-10,20:00,La Liga,Matchweek 31,Fri,Home,D,1,1,Girona,22,9,9,10,2,0,2025-2026,Real Madrid
2026-04-21,20:30,La Liga,Matchweek 32,Tue,Home,W,2,1,Alaves,24,8,14,9,1,0,2025-2026,Real Madrid
2026-04-24,20:00,La Liga,Matchweek 33,Fri,Away,D,1,1,Betis,12,8,8,6,2,0,2025-2026,Real Madrid
2026-05-03,20:00,La Liga,Matchweek 34,Sun,Away,W,2,0,Espanol,15,5,16,6,4,0,2025-2026,Real Madrid
2026-05-10,20:00,La Liga,Matchweek 35,Sun,Away,L,0,2,Barcelona,8,1,9,8,4,0,2025-2026,Real Madrid
2026-05-14,20:30,La Liga,Matchweek 36,Thu,Home,W,2,0,Oviedo,19,7,7,4,0,0,2025-2026,Real Madrid
2026-05-17,18:00,La Liga,Matchweek 37,Sun,Away,W,1,0,Sevilla,12,1,12,4,0,0,2025-2026,Real Madrid
2026-05-23,20:00,La Liga,Matchweek 38,Sat,Home,W,4,2,Ath Bilbao,13,8,6,2,2,0,2025-2026,Real Madrid

In [12]:
matches["round"].value_counts()

round
Matchweek 1     20
Matchweek 2     20
Matchweek 3     20
Matchweek 4     20
Matchweek 5     20
Matchweek 6     20
Matchweek 7     20
Matchweek 8     20
Matchweek 9     20
Matchweek 10    20
Matchweek 11    20
Matchweek 12    20
Matchweek 13    20
Matchweek 14    20
Matchweek 15    20
Matchweek 16    20
Matchweek 17    20
Matchweek 18    20
Matchweek 19    20
Matchweek 20    20
Matchweek 21    20
Matchweek 22    20
Matchweek 23    20
Matchweek 24    20
Matchweek 25    20
Matchweek 26    20
Matchweek 27    20
Matchweek 28    20
Matchweek 29    20
Matchweek 30    20
Matchweek 31    20
Matchweek 32    20
Matchweek 33    20
Matchweek 34    20
Matchweek 35    20
Matchweek 36    20
Matchweek 37    20
Matchweek 38    20
Name: count, dtype: int64

In [13]:
matches.dtypes

time          str
comp          str
round         str
day           str
venue         str
result        str
gf          int64
ga          int64
opponent      str
sh          int64
sot         int64
fouls       int64
corners     int64
yellow      int64
red         int64
season        str
team          str
dtype: object

In [14]:
matches["time"] = pd.to_datetime(matches["time"])

/var/folders/8q/20mf2pfj10j8dfwtpgwksnpc0000gn/T/ipykernel_60301/3153195306.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  matches["time"] = pd.to_datetime(matches["time"])

In [15]:
matches.dtypes

time        datetime64[us]
comp                   str
round                  str
day                    str
venue                  str
result                 str
gf                   int64
ga                   int64
opponent               str
sh                   int64
sot                  int64
fouls                int64
corners              int64
yellow               int64
red                  int64
season                 str
team                   str
dtype: object

In [19]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes
matches

,time,comp,round,day,venue,result,gf,ga,opponent,sh,sot,fouls,corners,yellow,red,season,team,venue_code
date,,,,,,,,,,,,,,,,,,
2025-08-15,2026-06-30 18:00:00,La Liga,Matchweek 1,Fri,1,L,1,3,Vallecano,7,2,8,2,0,1,2025-2026,Girona,1
2025-08-15,2026-06-30 18:00:00,La Liga,Matchweek 1,Fri,0,W,3,1,Girona,16,5,17,4,1,0,2025-2026,Vallecano,0
2025-08-15,2026-06-30 20:30:00,La Liga,Matchweek 1,Fri,0,L,0,2,Villarreal,5,4,8,1,2,1,2025-2026,Oviedo,0
2025-08-15,2026-06-30 20:30:00,La Liga,Matchweek 1,Fri,1,W,2,0,Oviedo,25,10,10,10,1,0,2025-2026,Villarreal,1
2025-08-16,2026-06-30 18:30:00,La Liga,Matchweek 1,Sat,0,W,3,0,Mallorca,24,8,17,6,1,0,2025-2026,Barcelona,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-05-23,2026-06-30 20:00:00,La Liga,Matchweek 38,Sat,0,D,1,1,Espanol,9,4,17,5,3,0,2025-2026,Sociedad,0
2026-05-23,2026-06-30 20:00:00,La Liga,Matchweek 38,Sat,1,W,3,1,Barcelona,19,6,11,7,2,0,2025-2026,Valencia,1
2026-05-23,2026-06-30 20:00:00,La Liga,Matchweek 38,Sat,0,W,2,1,Alaves,15,7,14,5,3,0,2025-2026,Vallecano,0
2026-05-24,2026-06-30 20:00:00,La Liga,Matchweek 38,Sun,0,L,1,5,Villarreal,9,4,12,9,1,0,2025-2026,Ath Madrid,0
2026-05-24,2026-06-30 20:00:00,La Liga,Matchweek 38,Sun,1,W,5,1,Ath Madrid,14,8,3,5,0,0,2025-2026,Villarreal,1

In [21]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes
matches

,time,comp,round,day,venue,result,gf,ga,opponent,sh,sot,fouls,corners,yellow,red,season,team,venue_code,opp_code
date,,,,,,,,,,,,,,,,,,,
2025-08-15,2026-06-30 18:00:00,La Liga,Matchweek 1,Fri,1,L,1,3,Vallecano,7,2,8,2,0,1,2025-2026,Girona,1,18
2025-08-15,2026-06-30 18:00:00,La Liga,Matchweek 1,Fri,0,W,3,1,Girona,16,5,17,4,1,0,2025-2026,Vallecano,0,9
2025-08-15,2026-06-30 20:30:00,La Liga,Matchweek 1,Fri,0,L,0,2,Villarreal,5,4,8,1,2,1,2025-2026,Oviedo,0,19
2025-08-15,2026-06-30 20:30:00,La Liga,Matchweek 1,Fri,1,W,2,0,Oviedo,25,10,10,10,1,0,2025-2026,Villarreal,1,13
2025-08-16,2026-06-30 18:30:00,La Liga,Matchweek 1,Sat,0,W,3,0,Mallorca,24,8,17,6,1,0,2025-2026,Barcelona,0,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-05-23,2026-06-30 20:00:00,La Liga,Matchweek 38,Sat,0,D,1,1,Espanol,9,4,17,5,3,0,2025-2026,Sociedad,0,7
2026-05-23,2026-06-30 20:00:00,La Liga,Matchweek 38,Sat,1,W,3,1,Barcelona,19,6,11,7,2,0,2025-2026,Valencia,1,3
2026-05-23,2026-06-30 20:00:00,La Liga,Matchweek 38,Sat,0,W,2,1,Alaves,15,7,14,5,3,0,2025-2026,Vallecano,0,0
2026-05-24,2026-06-30 20:00:00,La Liga,Matchweek 38,Sun,0,L,1,5,Villarreal,9,4,12,9,1,0,2025-2026,Ath Madrid,0,19
2026-05-24,2026-06-30 20:00:00,La Liga,Matchweek 38,Sun,1,W,5,1,Ath Madrid,14,8,3,5,0,0,2025-2026,Villarreal,1,2

In [28]:
matches["day_code"] = pd.to_datetime(matches.index).dayofweek
matches

,time,comp,round,day,venue,result,gf,ga,opponent,sh,sot,fouls,corners,yellow,red,season,team,venue_code,opp_code,day_code
date,,,,,,,,,,,,,,,,,,,,
2025-08-15,2026-06-30 18:00:00,La Liga,Matchweek 1,Fri,1,L,1,3,Vallecano,7,2,8,2,0,1,2025-2026,Girona,1,18,4
2025-08-15,2026-06-30 18:00:00,La Liga,Matchweek 1,Fri,0,W,3,1,Girona,16,5,17,4,1,0,2025-2026,Vallecano,0,9,4
2025-08-15,2026-06-30 20:30:00,La Liga,Matchweek 1,Fri,0,L,0,2,Villarreal,5,4,8,1,2,1,2025-2026,Oviedo,0,19,4
2025-08-15,2026-06-30 20:30:00,La Liga,Matchweek 1,Fri,1,W,2,0,Oviedo,25,10,10,10,1,0,2025-2026,Villarreal,1,13,4
2025-08-16,2026-06-30 18:30:00,La Liga,Matchweek 1,Sat,0,W,3,0,Mallorca,24,8,17,6,1,0,2025-2026,Barcelona,0,11,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-05-23,2026-06-30 20:00:00,La Liga,Matchweek 38,Sat,0,D,1,1,Espanol,9,4,17,5,3,0,2025-2026,Sociedad,0,7,5
2026-05-23,2026-06-30 20:00:00,La Liga,Matchweek 38,Sat,1,W,3,1,Barcelona,19,6,11,7,2,0,2025-2026,Valencia,1,3,5
2026-05-23,2026-06-30 20:00:00,La Liga,Matchweek 38,Sat,0,W,2,1,Alaves,15,7,14,5,3,0,2025-2026,Vallecano,0,0,5
2026-05-24,2026-06-30 20:00:00,La Liga,Matchweek 38,Sun,0,L,1,5,Villarreal,9,4,12,9,1,0,2025-2026,Ath Madrid,0,19,6
2026-05-24,2026-06-30 20:00:00,La Liga,Matchweek 38,Sun,1,W,5,1,Ath Madrid,14,8,3,5,0,0,2025-2026,Villarreal,1,2,6