In [3]:
import pandas as pd 
matches = pd.read_csv("matches_laliga_2025_2026.csv" , index_col=0)
matches.head()
matches.index = pd.to_datetime(matches.index)

In [4]:
matches.shape

(760, 17)

In [5]:
matches["team"].value_counts()

team
Girona         38
Vallecano      38
Oviedo         38
Villarreal     38
Barcelona      38
Mallorca       38
Alaves         38
Levante        38
Sociedad       38
Valencia       38
Celta          38
Getafe         38
Ath Bilbao     38
Sevilla        38
Ath Madrid     38
Espanol        38
Betis          38
Elche          38
Osasuna        38
Real Madrid    38
Name: count, dtype: int64

In [6]:
38 * 20 * 2

1520

In [7]:
matches[matches["team"] == "Real Madrid"]

,time,comp,round,day,venue,result,gf,ga,opponent,sh,sot,fouls,corners,yellow,red,season,team
date,,,,,,,,,,,,,,,,,
2025-08-19,20:00,La Liga,Matchweek 1,Tue,Home,W,1,0,Osasuna,18,5,10,7,1,0,2025-2026,Real Madrid
2025-08-24,20:30,La Liga,Matchweek 2,Sun,Away,W,3,0,Oviedo,26,10,7,9,1,0,2025-2026,Real Madrid
2025-08-30,20:30,La Liga,Matchweek 3,Sat,Home,W,2,1,Mallorca,17,7,12,4,2,0,2025-2026,Real Madrid
2025-09-13,15:15,La Liga,Matchweek 4,Sat,Away,W,2,1,Sociedad,16,6,7,4,1,1,2025-2026,Real Madrid
2025-09-20,15:15,La Liga,Matchweek 5,Sat,Home,W,2,0,Espanol,16,5,10,5,2,0,2025-2026,Real Madrid
2025-09-23,20:30,La Liga,Matchweek 6,Tue,Away,W,4,1,Levante,24,10,9,7,1,0,2025-2026,Real Madrid
2025-09-27,15:15,La Liga,Matchweek 7,Sat,Away,L,2,5,Ath Madrid,6,2,14,2,4,0,2025-2026,Real Madrid
2025-10-04,20:00,La Liga,Matchweek 8,Sat,Home,W,3,1,Villarreal,26,7,9,4,2,0,2025-2026,Real Madrid
2025-10-19,20:00,La Liga,Matchweek 9,Sun,Away,W,1,0,Getafe,23,10,11,4,1,0,2025-2026,Real Madrid
2025-10-26,15:15,La Liga,Matchweek 10,Sun,Home,W,2,1,Barcelona,23,10,12,12,5,1,2025-2026,Real Madrid
2025-11-01,20:00,La Liga,Matchweek 11,Sat,Home,W,4,0,Valencia,21,11,14,7,1,0,2025-2026,Real Madrid
2025-11-09,15:15,La Liga,Matchweek 12,Sun,Away,D,0,0,Vallecano,21,5,7,8,2,0,2025-2026,Real Madrid
2025-11-23,20:00,La Liga,Matchweek 13,Sun,Away,D,2,2,Elche,20,7,8,8,0,0,2025-2026,Real Madrid
2025-11-30,20:00,La Liga,Matchweek 14,Sun,Away,D,1,1,Girona,25,4,13,5,0,0,2025-2026,Real Madrid
2025-12-03,18:00,La Liga,Matchweek 15,Wed,Away,W,3,0,Ath Bilbao,13,8,4,7,0,0,2025-2026,Real Madrid
2025-12-07,20:00,La Liga,Matchweek 16,Sun,Home,L,0,2,Celta,23,7,6,8,6,3,2025-2026,Real Madrid
2025-12-14,20:00,La Liga,Matchweek 17,Sun,Away,W,2,1,Alaves,13,6,13,7,1,0,2025-2026,Real Madrid
2025-12-20,20:00,La Liga,Matchweek 18,Sat,Home,W,2,0,Sevilla,18,8,13,6,2,0,2025-2026,Real Madrid
2026-01-04,15:15,La Liga,Matchweek 19,Sun,Home,W,5,1,Betis,19,9,10,5,1,0,2025-2026,Real Madrid
2026-01-17,13:00,La Liga,Matchweek 20,Sat,Home,W,2,0,Levante,26,11,12,8,2,0,2025-2026,Real Madrid
2026-01-24,20:00,La Liga,Matchweek 21,Sat,Away,W,2,0,Villarreal,14,4,10,6,1,0,2025-2026,Real Madrid
2026-02-01,13:00,La Liga,Matchweek 22,Sun,Home,W,2,1,Vallecano,16,6,6,9,2,0,2025-2026,Real Madrid
2026-02-08,20:00,La Liga,Matchweek 23,Sun,Away,W,2,0,Valencia,11,6,13,8,1,0,2025-2026,Real Madrid
2026-02-14,20:00,La Liga,Matchweek 24,Sat,Home,W,4,1,Sociedad,11,5,10,4,1,0,2025-2026,Real Madrid
2026-02-21,17:30,La Liga,Matchweek 25,Sat,Away,L,1,2,Osasuna,15,5,10,7,4,0,2025-2026,Real Madrid
2026-03-02,20:00,La Liga,Matchweek 26,Mon,Home,L,0,1,Getafe,18,7,11,10,4,1,2025-2026,Real Madrid
2026-03-06,20:00,La Liga,Matchweek 27,Fri,Away,W,2,1,Celta,14,3,12,6,2,0,2025-2026,Real Madrid
2026-03-14,20:00,La Liga,Matchweek 28,Sat,Home,W,4,1,Elche,14,6,11,5,1,0,2025-2026,Real Madrid
2026-03-22,20:00,La Liga,Matchweek 29,Sun,Home,W,3,2,Ath Madrid,17,10,2,4,1,1,2025-2026,Real Madrid
2026-04-04,15:15,La Liga,Matchweek 30,Sat,Away,L,1,2,Mallorca,15,6,13,4,2,0,2025-2026,Real Madrid
2026-04-10,20:00,La Liga,Matchweek 31,Fri,Home,D,1,1,Girona,22,9,9,10,2,0,2025-2026,Real Madrid
2026-04-21,20:30,La Liga,Matchweek 32,Tue,Home,W,2,1,Alaves,24,8,14,9,1,0,2025-2026,Real Madrid
2026-04-24,20:00,La Liga,Matchweek 33,Fri,Away,D,1,1,Betis,12,8,8,6,2,0,2025-2026,Real Madrid
2026-05-03,20:00,La Liga,Matchweek 34,Sun,Away,W,2,0,Espanol,15,5,16,6,4,0,2025-2026,Real Madrid
2026-05-10,20:00,La Liga,Matchweek 35,Sun,Away,L,0,2,Barcelona,8,1,9,8,4,0,2025-2026,Real Madrid
2026-05-14,20:30,La Liga,Matchweek 36,Thu,Home,W,2,0,Oviedo,19,7,7,4,0,0,2025-2026,Real Madrid
2026-05-17,18:00,La Liga,Matchweek 37,Sun,Away,W,1,0,Sevilla,12,1,12,4,0,0,2025-2026,Real Madrid
2026-05-23,20:00,La Liga,Matchweek 38,Sat,Home,W,4,2,Ath Bilbao,13,8,6,2,2,0,2025-2026,Real Madrid

In [8]:
matches["round"].value_counts()

round
Matchweek 1     20
Matchweek 2     20
Matchweek 3     20
Matchweek 4     20
Matchweek 5     20
Matchweek 6     20
Matchweek 7     20
Matchweek 8     20
Matchweek 9     20
Matchweek 10    20
Matchweek 11    20
Matchweek 12    20
Matchweek 13    20
Matchweek 14    20
Matchweek 15    20
Matchweek 16    20
Matchweek 17    20
Matchweek 18    20
Matchweek 19    20
Matchweek 20    20
Matchweek 21    20
Matchweek 22    20
Matchweek 23    20
Matchweek 24    20
Matchweek 25    20
Matchweek 26    20
Matchweek 27    20
Matchweek 28    20
Matchweek 29    20
Matchweek 30    20
Matchweek 31    20
Matchweek 32    20
Matchweek 33    20
Matchweek 34    20
Matchweek 35    20
Matchweek 36    20
Matchweek 37    20
Matchweek 38    20
Name: count, dtype: int64

In [9]:
matches.dtypes

time          str
comp          str
round         str
day           str
venue         str
result        str
gf          int64
ga          int64
opponent      str
sh          int64
sot         int64
fouls       int64
corners     int64
yellow      int64
red         int64
season        str
team          str
dtype: object

In [10]:
matches["time"] = pd.to_datetime(matches["time"], format="%H:%M")
matches["hour"] = matches["time"].dt.hour

In [11]:
matches.dtypes

time        datetime64[us]
comp                   str
round                  str
day                    str
venue                  str
result                 str
gf                   int64
ga                   int64
opponent               str
sh                   int64
sot                  int64
fouls                int64
corners              int64
yellow               int64
red                  int64
season                 str
team                   str
hour                 int32
dtype: object

In [12]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes
matches

,time,comp,round,day,venue,result,gf,ga,opponent,sh,sot,fouls,corners,yellow,red,season,team,hour,venue_code
date,,,,,,,,,,,,,,,,,,,
2025-08-15,1900-01-01 18:00:00,La Liga,Matchweek 1,Fri,Home,L,1,3,Vallecano,7,2,8,2,0,1,2025-2026,Girona,18,1
2025-08-15,1900-01-01 18:00:00,La Liga,Matchweek 1,Fri,Away,W,3,1,Girona,16,5,17,4,1,0,2025-2026,Vallecano,18,0
2025-08-15,1900-01-01 20:30:00,La Liga,Matchweek 1,Fri,Away,L,0,2,Villarreal,5,4,8,1,2,1,2025-2026,Oviedo,20,0
2025-08-15,1900-01-01 20:30:00,La Liga,Matchweek 1,Fri,Home,W,2,0,Oviedo,25,10,10,10,1,0,2025-2026,Villarreal,20,1
2025-08-16,1900-01-01 18:30:00,La Liga,Matchweek 1,Sat,Away,W,3,0,Mallorca,24,8,17,6,1,0,2025-2026,Barcelona,18,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-05-23,1900-01-01 20:00:00,La Liga,Matchweek 38,Sat,Away,D,1,1,Espanol,9,4,17,5,3,0,2025-2026,Sociedad,20,0
2026-05-23,1900-01-01 20:00:00,La Liga,Matchweek 38,Sat,Home,W,3,1,Barcelona,19,6,11,7,2,0,2025-2026,Valencia,20,1
2026-05-23,1900-01-01 20:00:00,La Liga,Matchweek 38,Sat,Away,W,2,1,Alaves,15,7,14,5,3,0,2025-2026,Vallecano,20,0
2026-05-24,1900-01-01 20:00:00,La Liga,Matchweek 38,Sun,Away,L,1,5,Villarreal,9,4,12,9,1,0,2025-2026,Ath Madrid,20,0
2026-05-24,1900-01-01 20:00:00,La Liga,Matchweek 38,Sun,Home,W,5,1,Ath Madrid,14,8,3,5,0,0,2025-2026,Villarreal,20,1

In [13]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes
matches

,time,comp,round,day,venue,result,gf,ga,opponent,sh,sot,fouls,corners,yellow,red,season,team,hour,venue_code,opp_code
date,,,,,,,,,,,,,,,,,,,,
2025-08-15,1900-01-01 18:00:00,La Liga,Matchweek 1,Fri,Home,L,1,3,Vallecano,7,2,8,2,0,1,2025-2026,Girona,18,1,18
2025-08-15,1900-01-01 18:00:00,La Liga,Matchweek 1,Fri,Away,W,3,1,Girona,16,5,17,4,1,0,2025-2026,Vallecano,18,0,9
2025-08-15,1900-01-01 20:30:00,La Liga,Matchweek 1,Fri,Away,L,0,2,Villarreal,5,4,8,1,2,1,2025-2026,Oviedo,20,0,19
2025-08-15,1900-01-01 20:30:00,La Liga,Matchweek 1,Fri,Home,W,2,0,Oviedo,25,10,10,10,1,0,2025-2026,Villarreal,20,1,13
2025-08-16,1900-01-01 18:30:00,La Liga,Matchweek 1,Sat,Away,W,3,0,Mallorca,24,8,17,6,1,0,2025-2026,Barcelona,18,0,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-05-23,1900-01-01 20:00:00,La Liga,Matchweek 38,Sat,Away,D,1,1,Espanol,9,4,17,5,3,0,2025-2026,Sociedad,20,0,7
2026-05-23,1900-01-01 20:00:00,La Liga,Matchweek 38,Sat,Home,W,3,1,Barcelona,19,6,11,7,2,0,2025-2026,Valencia,20,1,3
2026-05-23,1900-01-01 20:00:00,La Liga,Matchweek 38,Sat,Away,W,2,1,Alaves,15,7,14,5,3,0,2025-2026,Vallecano,20,0,0
2026-05-24,1900-01-01 20:00:00,La Liga,Matchweek 38,Sun,Away,L,1,5,Villarreal,9,4,12,9,1,0,2025-2026,Ath Madrid,20,0,19
2026-05-24,1900-01-01 20:00:00,La Liga,Matchweek 38,Sun,Home,W,5,1,Ath Madrid,14,8,3,5,0,0,2025-2026,Villarreal,20,1,2

In [14]:
matches["day_code"] = pd.to_datetime(matches.index).dayofweek
matches

,time,comp,round,day,venue,result,gf,ga,opponent,sh,...,fouls,corners,yellow,red,season,team,hour,venue_code,opp_code,day_code
date,,,,,,,,,,,,,,,,,,,,,
2025-08-15,1900-01-01 18:00:00,La Liga,Matchweek 1,Fri,Home,L,1,3,Vallecano,7,...,8,2,0,1,2025-2026,Girona,18,1,18,4
2025-08-15,1900-01-01 18:00:00,La Liga,Matchweek 1,Fri,Away,W,3,1,Girona,16,...,17,4,1,0,2025-2026,Vallecano,18,0,9,4
2025-08-15,1900-01-01 20:30:00,La Liga,Matchweek 1,Fri,Away,L,0,2,Villarreal,5,...,8,1,2,1,2025-2026,Oviedo,20,0,19,4
2025-08-15,1900-01-01 20:30:00,La Liga,Matchweek 1,Fri,Home,W,2,0,Oviedo,25,...,10,10,1,0,2025-2026,Villarreal,20,1,13,4
2025-08-16,1900-01-01 18:30:00,La Liga,Matchweek 1,Sat,Away,W,3,0,Mallorca,24,...,17,6,1,0,2025-2026,Barcelona,18,0,11,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-05-23,1900-01-01 20:00:00,La Liga,Matchweek 38,Sat,Away,D,1,1,Espanol,9,...,17,5,3,0,2025-2026,Sociedad,20,0,7,5
2026-05-23,1900-01-01 20:00:00,La Liga,Matchweek 38,Sat,Home,W,3,1,Barcelona,19,...,11,7,2,0,2025-2026,Valencia,20,1,3,5
2026-05-23,1900-01-01 20:00:00,La Liga,Matchweek 38,Sat,Away,W,2,1,Alaves,15,...,14,5,3,0,2025-2026,Vallecano,20,0,0,5
2026-05-24,1900-01-01 20:00:00,La Liga,Matchweek 38,Sun,Away,L,1,5,Villarreal,9,...,12,9,1,0,2025-2026,Ath Madrid,20,0,19,6
2026-05-24,1900-01-01 20:00:00,La Liga,Matchweek 38,Sun,Home,W,5,1,Ath Madrid,14,...,3,5,0,0,2025-2026,Villarreal,20,1,2,6

In [15]:
matches["target"] = (matches["result"] == "W").astype(int)
matches

,time,comp,round,day,venue,result,gf,ga,opponent,sh,...,corners,yellow,red,season,team,hour,venue_code,opp_code,day_code,target
date,,,,,,,,,,,,,,,,,,,,,
2025-08-15,1900-01-01 18:00:00,La Liga,Matchweek 1,Fri,Home,L,1,3,Vallecano,7,...,2,0,1,2025-2026,Girona,18,1,18,4,0
2025-08-15,1900-01-01 18:00:00,La Liga,Matchweek 1,Fri,Away,W,3,1,Girona,16,...,4,1,0,2025-2026,Vallecano,18,0,9,4,1
2025-08-15,1900-01-01 20:30:00,La Liga,Matchweek 1,Fri,Away,L,0,2,Villarreal,5,...,1,2,1,2025-2026,Oviedo,20,0,19,4,0
2025-08-15,1900-01-01 20:30:00,La Liga,Matchweek 1,Fri,Home,W,2,0,Oviedo,25,...,10,1,0,2025-2026,Villarreal,20,1,13,4,1
2025-08-16,1900-01-01 18:30:00,La Liga,Matchweek 1,Sat,Away,W,3,0,Mallorca,24,...,6,1,0,2025-2026,Barcelona,18,0,11,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-05-23,1900-01-01 20:00:00,La Liga,Matchweek 38,Sat,Away,D,1,1,Espanol,9,...,5,3,0,2025-2026,Sociedad,20,0,7,5,0
2026-05-23,1900-01-01 20:00:00,La Liga,Matchweek 38,Sat,Home,W,3,1,Barcelona,19,...,7,2,0,2025-2026,Valencia,20,1,3,5,1
2026-05-23,1900-01-01 20:00:00,La Liga,Matchweek 38,Sat,Away,W,2,1,Alaves,15,...,5,3,0,2025-2026,Vallecano,20,0,0,5,1
2026-05-24,1900-01-01 20:00:00,La Liga,Matchweek 38,Sun,Away,L,1,5,Villarreal,9,...,9,1,0,2025-2026,Ath Madrid,20,0,19,6,0
2026-05-24,1900-01-01 20:00:00,La Liga,Matchweek 38,Sun,Home,W,5,1,Ath Madrid,14,...,5,0,0,2025-2026,Villarreal,20,1,2,6,1

In [16]:
from sklearn.ensemble import RandomForestClassifier

In [17]:
rf = RandomForestClassifier(n_estimators=100, min_samples_split=2, random_state=1)

In [18]:
train = matches[matches.index < "2026-01-01"]

In [19]:
test = matches[matches.index >= "2026-01-01"]

In [20]:
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [21]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(random_state=1)

In [22]:
RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [23]:
preds = rf.predict(test[predictors])

In [24]:
from sklearn.metrics import accuracy_score

In [25]:
acc = accuracy_score(test["target"], preds)

In [26]:
acc

0.5956937799043063

In [27]:
combined = pd.DataFrame({
    "actual": test["target"].to_numpy(),
    "prediction": preds
})

pd.crosstab(
    index=combined["actual"],
    columns=combined["prediction"]
)

prediction    0   1
actual
0           185  74
1            95  64

In [28]:
combined = pd.DataFrame({
    "actual": test["target"].to_numpy(),
    "prediction": preds
})

In [29]:
pd.crosstab(
    index=combined["actual"],
    columns=combined["prediction"]
)

prediction    0   1
actual
0           185  74
1            95  64

In [30]:
from sklearn.metrics import precision_score
precision_score(test["target"], preds)

0.463768115942029

In [31]:
grouped_matches = matches.groupby("team")

In [32]:
group = grouped_matches.get_group("Real Madrid")

In [33]:
group

,time,comp,round,day,venue,result,gf,ga,opponent,sh,...,corners,yellow,red,season,team,hour,venue_code,opp_code,day_code,target
date,,,,,,,,,,,,,,,,,,,,,
2025-08-19,1900-01-01 20:00:00,La Liga,Matchweek 1,Tue,Home,W,1,0,Osasuna,18,...,7,1,0,2025-2026,Real Madrid,20,1,12,1,1
2025-08-24,1900-01-01 20:30:00,La Liga,Matchweek 2,Sun,Away,W,3,0,Oviedo,26,...,9,1,0,2025-2026,Real Madrid,20,0,13,6,1
2025-08-30,1900-01-01 20:30:00,La Liga,Matchweek 3,Sat,Home,W,2,1,Mallorca,17,...,4,2,0,2025-2026,Real Madrid,20,1,11,5,1
2025-09-13,1900-01-01 15:15:00,La Liga,Matchweek 4,Sat,Away,W,2,1,Sociedad,16,...,4,1,1,2025-2026,Real Madrid,15,0,16,5,1
2025-09-20,1900-01-01 15:15:00,La Liga,Matchweek 5,Sat,Home,W,2,0,Espanol,16,...,5,2,0,2025-2026,Real Madrid,15,1,7,5,1
2025-09-23,1900-01-01 20:30:00,La Liga,Matchweek 6,Tue,Away,W,4,1,Levante,24,...,7,1,0,2025-2026,Real Madrid,20,0,10,1,1
2025-09-27,1900-01-01 15:15:00,La Liga,Matchweek 7,Sat,Away,L,2,5,Ath Madrid,6,...,2,4,0,2025-2026,Real Madrid,15,0,2,5,0
2025-10-04,1900-01-01 20:00:00,La Liga,Matchweek 8,Sat,Home,W,3,1,Villarreal,26,...,4,2,0,2025-2026,Real Madrid,20,1,19,5,1
2025-10-19,1900-01-01 20:00:00,La Liga,Matchweek 9,Sun,Away,W,1,0,Getafe,23,...,4,1,0,2025-2026,Real Madrid,20,0,8,6,1
2025-10-26,1900-01-01 15:15:00,La Liga,Matchweek 10,Sun,Home,W,2,1,Barcelona,23,...,12,5,1,2025-2026,Real Madrid,15,1,3,6,1
2025-11-01,1900-01-01 20:00:00,La Liga,Matchweek 11,Sat,Home,W,4,0,Valencia,21,...,7,1,0,2025-2026,Real Madrid,20,1,17,5,1
2025-11-09,1900-01-01 15:15:00,La Liga,Matchweek 12,Sun,Away,D,0,0,Vallecano,21,...,8,2,0,2025-2026,Real Madrid,15,0,18,6,0
2025-11-23,1900-01-01 20:00:00,La Liga,Matchweek 13,Sun,Away,D,2,2,Elche,20,...,8,0,0,2025-2026,Real Madrid,20,0,6,6,0
2025-11-30,1900-01-01 20:00:00,La Liga,Matchweek 14,Sun,Away,D,1,1,Girona,25,...,5,0,0,2025-2026,Real Madrid,20,0,9,6,0
2025-12-03,1900-01-01 18:00:00,La Liga,Matchweek 15,Wed,Away,W,3,0,Ath Bilbao,13,...,7,0,0,2025-2026,Real Madrid,18,0,1,2,1
2025-12-07,1900-01-01 20:00:00,La Liga,Matchweek 16,Sun,Home,L,0,2,Celta,23,...,8,6,3,2025-2026,Real Madrid,20,1,5,6,0
2025-12-14,1900-01-01 20:00:00,La Liga,Matchweek 17,Sun,Away,W,2,1,Alaves,13,...,7,1,0,2025-2026,Real Madrid,20,0,0,6,1
2025-12-20,1900-01-01 20:00:00,La Liga,Matchweek 18,Sat,Home,W,2,0,Sevilla,18,...,6,2,0,2025-2026,Real Madrid,20,1,15,5,1
2026-01-04,1900-01-01 15:15:00,La Liga,Matchweek 19,Sun,Home,W,5,1,Betis,19,...,5,1,0,2025-2026,Real Madrid,15,1,4,6,1
2026-01-17,1900-01-01 13:00:00,La Liga,Matchweek 20,Sat,Home,W,2,0,Levante,26,...,8,2,0,2025-2026,Real Madrid,13,1,10,5,1
2026-01-24,1900-01-01 20:00:00,La Liga,Matchweek 21,Sat,Away,W,2,0,Villarreal,14,...,6,1,0,2025-2026,Real Madrid,20,0,19,5,1
2026-02-01,1900-01-01 13:00:00,La Liga,Matchweek 22,Sun,Home,W,2,1,Vallecano,16,...,9,2,0,2025-2026,Real Madrid,13,1,18,6,1
2026-02-08,1900-01-01 20:00:00,La Liga,Matchweek 23,Sun,Away,W,2,0,Valencia,11,...,8,1,0,2025-2026,Real Madrid,20,0,17,6,1
2026-02-14,1900-01-01 20:00:00,La Liga,Matchweek 24,Sat,Home,W,4,1,Sociedad,11,...,4,1,0,2025-2026,Real Madrid,20,1,16,5,1
2026-02-21,1900-01-01 17:30:00,La Liga,Matchweek 25,Sat,Away,L,1,2,Osasuna,15,...,7,4,0,2025-2026,Real Madrid,17,0,12,5,0
2026-03-02,1900-01-01 20:00:00,La Liga,Matchweek 26,Mon,Home,L,0,1,Getafe,18,...,10,4,1,2025-2026,Real Madrid,20,1,8,0,0
2026-03-06,1900-01-01 20:00:00,La Liga,Matchweek 27,Fri,Away,W,2,1,Celta,14,...,6,2,0,2025-2026,Real Madrid,20,0,5,4,1
2026-03-14,1900-01-01 20:00:00,La Liga,Matchweek 28,Sat,Home,W,4,1,Elche,14,...,5,1,0,2025-2026,Real Madrid,20,1,6,5,1
2026-03-22,1900-01-01 20:00:00,La Liga,Matchweek 29,Sun,Home,W,3,2,Ath Madrid,17,...,4,1,1,2025-2026,Real Madrid,20,1,2,6,1
2026-04-04,1900-01-01 15:15:00,La Liga,Matchweek 30,Sat,Away,L,1,2,Mallorca,15,...,4,2,0,2025-2026,Real Madrid,15,0,11,5,0
2026-04-10,1900-01-01 20:00:00,La Liga,Matchweek 31,Fri,Home,D,1,1,Girona,22,...,10,2,0,2025-2026,Real Madrid,20,1,9,4,0
2026-04-21,1900-01-01 20:30:00,La Liga,Matchweek 32,Tue,Home,W,2,1,Alaves,24,...,9,1,0,2025-2026,Real Madrid,20,1,0,1,1
2026-04-24,1900-01-01 20:00:00,La Liga,Matchweek 33,Fri,Away,D,1,1,Betis,12,...,6,2,0,2025-2026,Real Madrid,20,0,4,4,0
2026-05-03,1900-01-01 20:00:00,La Liga,Matchweek 34,Sun,Away,W,2,0,Espanol,15,...,6,4,0,2025-2026,Real Madrid,20,0,7,6,1
2026-05-10,1900-01-01 20:00:00,La Liga,Matchweek 35,Sun,Away,L,0,2,Barcelona,8,...,8,4,0,2025-2026,Real Madrid,20,0,3,6,0
2026-05-14,1900-01-01 20:30:00,La Liga,Matchweek 36,Thu,Home,W,2,0,Oviedo,19,...,4,0,0,2025-2026,Real Madrid,20,1,13,3,1
2026-05-17,1900-01-01 18:00:00,La Liga,Matchweek 37,Sun,Away,W,1,0,Sevilla,12,...,4,0,0,2025-2026,Real Madrid,18,0,15,6,1
2026-05-23,1900-01-01 20:00:00,La Liga,Matchweek 38,Sat,Home,W,4,2,Ath Bilbao,13,...,2,2,0,2025-2026,Real Madrid,20,1,1,5,1

In [34]:
def rolling_average(group, cols, new_cols):
    group = group.sort_index().copy()
    group[new_cols] = group[cols].rolling(3, closed="left").mean()
    return group.dropna(subset=new_cols)

cols = ["gf", "ga", "sh", "sot", "fouls", "corners", "yellow", "red"]
new_cols = [f"{col}_rolling" for col in cols]

rolling_average(group, cols, new_cols)

,time,comp,round,day,venue,result,gf,ga,opponent,sh,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,fouls_rolling,corners_rolling,yellow_rolling,red_rolling
date,,,,,,,,,,,,,,,,,,,,,
2025-09-13,1900-01-01 15:15:00,La Liga,Matchweek 4,Sat,Away,W,2,1,Sociedad,16,...,5,1,2.000000,0.333333,20.333333,7.333333,9.666667,6.666667,1.333333,0.000000
2025-09-20,1900-01-01 15:15:00,La Liga,Matchweek 5,Sat,Home,W,2,0,Espanol,16,...,5,1,2.333333,0.666667,19.666667,7.666667,8.666667,5.666667,1.333333,0.333333
2025-09-23,1900-01-01 20:30:00,La Liga,Matchweek 6,Tue,Away,W,4,1,Levante,24,...,1,1,2.000000,0.666667,16.333333,6.000000,9.666667,4.333333,1.666667,0.333333
2025-09-27,1900-01-01 15:15:00,La Liga,Matchweek 7,Sat,Away,L,2,5,Ath Madrid,6,...,5,0,2.666667,0.666667,18.666667,7.000000,8.666667,5.333333,1.333333,0.333333
2025-10-04,1900-01-01 20:00:00,La Liga,Matchweek 8,Sat,Home,W,3,1,Villarreal,26,...,5,1,2.666667,2.000000,15.333333,5.666667,11.000000,4.666667,2.333333,0.000000
2025-10-19,1900-01-01 20:00:00,La Liga,Matchweek 9,Sun,Away,W,1,0,Getafe,23,...,6,1,3.000000,2.333333,18.666667,6.333333,10.666667,4.333333,2.333333,0.000000
2025-10-26,1900-01-01 15:15:00,La Liga,Matchweek 10,Sun,Home,W,2,1,Barcelona,23,...,6,1,2.000000,2.000000,18.333333,6.333333,11.333333,3.333333,2.333333,0.000000
2025-11-01,1900-01-01 20:00:00,La Liga,Matchweek 11,Sat,Home,W,4,0,Valencia,21,...,5,1,2.000000,0.666667,24.000000,9.000000,10.666667,6.666667,2.666667,0.333333
2025-11-09,1900-01-01 15:15:00,La Liga,Matchweek 12,Sun,Away,D,0,0,Vallecano,21,...,6,0,2.333333,0.333333,22.333333,10.333333,12.333333,7.666667,2.333333,0.333333
2025-11-23,1900-01-01 20:00:00,La Liga,Matchweek 13,Sun,Away,D,2,2,Elche,20,...,6,0,2.000000,0.333333,21.666667,8.666667,11.000000,9.000000,2.666667,0.333333
2025-11-30,1900-01-01 20:00:00,La Liga,Matchweek 14,Sun,Away,D,1,1,Girona,25,...,6,0,2.000000,0.666667,20.666667,7.666667,9.666667,7.666667,1.000000,0.000000
2025-12-03,1900-01-01 18:00:00,La Liga,Matchweek 15,Wed,Away,W,3,0,Ath Bilbao,13,...,2,1,1.000000,1.000000,22.000000,5.333333,9.333333,7.000000,0.666667,0.000000
2025-12-07,1900-01-01 20:00:00,La Liga,Matchweek 16,Sun,Home,L,0,2,Celta,23,...,6,0,2.000000,1.000000,19.333333,6.333333,8.333333,6.666667,0.000000,0.000000
2025-12-14,1900-01-01 20:00:00,La Liga,Matchweek 17,Sun,Away,W,2,1,Alaves,13,...,6,1,1.333333,1.000000,20.333333,6.333333,7.666667,6.666667,2.000000,1.000000
2025-12-20,1900-01-01 20:00:00,La Liga,Matchweek 18,Sat,Home,W,2,0,Sevilla,18,...,5,1,1.666667,1.000000,16.333333,7.000000,7.666667,7.333333,2.333333,1.000000
2026-01-04,1900-01-01 15:15:00,La Liga,Matchweek 19,Sun,Home,W,5,1,Betis,19,...,6,1,1.333333,1.000000,18.000000,7.000000,10.666667,7.000000,3.000000,1.000000
2026-01-17,1900-01-01 13:00:00,La Liga,Matchweek 20,Sat,Home,W,2,0,Levante,26,...,5,1,3.000000,0.666667,16.666667,7.666667,12.000000,6.000000,1.333333,0.000000
2026-01-24,1900-01-01 20:00:00,La Liga,Matchweek 21,Sat,Away,W,2,0,Villarreal,14,...,5,1,3.000000,0.333333,21.000000,9.333333,11.666667,6.333333,1.666667,0.000000
2026-02-01,1900-01-01 13:00:00,La Liga,Matchweek 22,Sun,Home,W,2,1,Vallecano,16,...,6,1,3.000000,0.333333,19.666667,8.000000,10.666667,6.333333,1.333333,0.000000
2026-02-08,1900-01-01 20:00:00,La Liga,Matchweek 23,Sun,Away,W,2,0,Valencia,11,...,6,1,2.000000,0.333333,18.666667,7.000000,9.333333,7.666667,1.666667,0.000000
2026-02-14,1900-01-01 20:00:00,La Liga,Matchweek 24,Sat,Home,W,4,1,Sociedad,11,...,5,1,2.000000,0.333333,13.666667,5.333333,9.666667,7.666667,1.333333,0.000000
2026-02-21,1900-01-01 17:30:00,La Liga,Matchweek 25,Sat,Away,L,1,2,Osasuna,15,...,5,0,2.666667,0.666667,12.666667,5.666667,9.666667,7.000000,1.333333,0.000000
2026-03-02,1900-01-01 20:00:00,La Liga,Matchweek 26,Mon,Home,L,0,1,Getafe,18,...,0,0,2.333333,1.000000,12.333333,5.333333,11.000000,6.333333,2.000000,0.000000
2026-03-06,1900-01-01 20:00:00,La Liga,Matchweek 27,Fri,Away,W,2,1,Celta,14,...,4,1,1.666667,1.333333,14.666667,5.666667,10.333333,7.000000,3.000000,0.333333
2026-03-14,1900-01-01 20:00:00,La Liga,Matchweek 28,Sat,Home,W,4,1,Elche,14,...,5,1,1.000000,1.333333,15.666667,5.000000,11.000000,7.666667,3.333333,0.333333
2026-03-22,1900-01-01 20:00:00,La Liga,Matchweek 29,Sun,Home,W,3,2,Ath Madrid,17,...,6,1,2.000000,1.000000,15.333333,5.333333,11.333333,7.000000,2.333333,0.333333
2026-04-04,1900-01-01 15:15:00,La Liga,Matchweek 30,Sat,Away,L,1,2,Mallorca,15,...,5,0,3.000000,1.333333,15.000000,6.333333,8.333333,5.000000,1.333333,0.333333
2026-04-10,1900-01-01 20:00:00,La Liga,Matchweek 31,Fri,Home,D,1,1,Girona,22,...,4,0,2.666667,1.666667,15.333333,7.333333,8.666667,4.333333,1.333333,0.333333
2026-04-21,1900-01-01 20:30:00,La Liga,Matchweek 32,Tue,Home,W,2,1,Alaves,24,...,1,1,1.666667,1.666667,18.000000,8.333333,8.000000,6.000000,1.666667,0.333333
2026-04-24,1900-01-01 20:00:00,La Liga,Matchweek 33,Fri,Away,D,1,1,Betis,12,...,4,0,1.333333,1.333333,20.333333,7.666667,12.000000,7.666667,1.666667,0.000000
2026-05-03,1900-01-01 20:00:00,La Liga,Matchweek 34,Sun,Away,W,2,0,Espanol,15,...,6,1,1.333333,1.000000,19.333333,8.333333,10.333333,8.333333,1.666667,0.000000
2026-05-10,1900-01-01 20:00:00,La Liga,Matchweek 35,Sun,Away,L,0,2,Barcelona,8,...,6,0,1.666667,0.666667,17.000000,7.000000,12.666667,7.000000,2.333333,0.000000
2026-05-14,1900-01-01 20:30:00,La Liga,Matchweek 36,Thu,Home,W,2,0,Oviedo,19,...,3,1,1.000000,1.000000,11.666667,4.666667,11.000000,6.666667,3.333333,0.000000
2026-05-17,1900-01-01 18:00:00,La Liga,Matchweek 37,Sun,Away,W,1,0,Sevilla,12,...,6,1,1.333333,0.666667,14.000000,4.333333,10.666667,6.000000,2.666667,0.000000
2026-05-23,1900-01-01 20:00:00,La Liga,Matchweek 38,Sat,Home,W,4,2,Ath Bilbao,13,...,5,1,1.000000,0.666667,13.000000,3.000000,9.333333,5.333333,1.333333,0.000000

In [35]:
cols = ["gf", "ga", "sh", "sot", "fouls", "corners", "yellow", "red"]
new_cols = [f"{col}_rolling" for col in cols]

In [36]:
new_cols

['gf_rolling',
 'ga_rolling',
 'sh_rolling',
 'sot_rolling',
 'fouls_rolling',
 'corners_rolling',
 'yellow_rolling',
 'red_rolling']

In [37]:
rolling_average(group, cols, new_cols)

,time,comp,round,day,venue,result,gf,ga,opponent,sh,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,fouls_rolling,corners_rolling,yellow_rolling,red_rolling
date,,,,,,,,,,,,,,,,,,,,,
2025-09-13,1900-01-01 15:15:00,La Liga,Matchweek 4,Sat,Away,W,2,1,Sociedad,16,...,5,1,2.000000,0.333333,20.333333,7.333333,9.666667,6.666667,1.333333,0.000000
2025-09-20,1900-01-01 15:15:00,La Liga,Matchweek 5,Sat,Home,W,2,0,Espanol,16,...,5,1,2.333333,0.666667,19.666667,7.666667,8.666667,5.666667,1.333333,0.333333
2025-09-23,1900-01-01 20:30:00,La Liga,Matchweek 6,Tue,Away,W,4,1,Levante,24,...,1,1,2.000000,0.666667,16.333333,6.000000,9.666667,4.333333,1.666667,0.333333
2025-09-27,1900-01-01 15:15:00,La Liga,Matchweek 7,Sat,Away,L,2,5,Ath Madrid,6,...,5,0,2.666667,0.666667,18.666667,7.000000,8.666667,5.333333,1.333333,0.333333
2025-10-04,1900-01-01 20:00:00,La Liga,Matchweek 8,Sat,Home,W,3,1,Villarreal,26,...,5,1,2.666667,2.000000,15.333333,5.666667,11.000000,4.666667,2.333333,0.000000
2025-10-19,1900-01-01 20:00:00,La Liga,Matchweek 9,Sun,Away,W,1,0,Getafe,23,...,6,1,3.000000,2.333333,18.666667,6.333333,10.666667,4.333333,2.333333,0.000000
2025-10-26,1900-01-01 15:15:00,La Liga,Matchweek 10,Sun,Home,W,2,1,Barcelona,23,...,6,1,2.000000,2.000000,18.333333,6.333333,11.333333,3.333333,2.333333,0.000000
2025-11-01,1900-01-01 20:00:00,La Liga,Matchweek 11,Sat,Home,W,4,0,Valencia,21,...,5,1,2.000000,0.666667,24.000000,9.000000,10.666667,6.666667,2.666667,0.333333
2025-11-09,1900-01-01 15:15:00,La Liga,Matchweek 12,Sun,Away,D,0,0,Vallecano,21,...,6,0,2.333333,0.333333,22.333333,10.333333,12.333333,7.666667,2.333333,0.333333
2025-11-23,1900-01-01 20:00:00,La Liga,Matchweek 13,Sun,Away,D,2,2,Elche,20,...,6,0,2.000000,0.333333,21.666667,8.666667,11.000000,9.000000,2.666667,0.333333
2025-11-30,1900-01-01 20:00:00,La Liga,Matchweek 14,Sun,Away,D,1,1,Girona,25,...,6,0,2.000000,0.666667,20.666667,7.666667,9.666667,7.666667,1.000000,0.000000
2025-12-03,1900-01-01 18:00:00,La Liga,Matchweek 15,Wed,Away,W,3,0,Ath Bilbao,13,...,2,1,1.000000,1.000000,22.000000,5.333333,9.333333,7.000000,0.666667,0.000000
2025-12-07,1900-01-01 20:00:00,La Liga,Matchweek 16,Sun,Home,L,0,2,Celta,23,...,6,0,2.000000,1.000000,19.333333,6.333333,8.333333,6.666667,0.000000,0.000000
2025-12-14,1900-01-01 20:00:00,La Liga,Matchweek 17,Sun,Away,W,2,1,Alaves,13,...,6,1,1.333333,1.000000,20.333333,6.333333,7.666667,6.666667,2.000000,1.000000
2025-12-20,1900-01-01 20:00:00,La Liga,Matchweek 18,Sat,Home,W,2,0,Sevilla,18,...,5,1,1.666667,1.000000,16.333333,7.000000,7.666667,7.333333,2.333333,1.000000
2026-01-04,1900-01-01 15:15:00,La Liga,Matchweek 19,Sun,Home,W,5,1,Betis,19,...,6,1,1.333333,1.000000,18.000000,7.000000,10.666667,7.000000,3.000000,1.000000
2026-01-17,1900-01-01 13:00:00,La Liga,Matchweek 20,Sat,Home,W,2,0,Levante,26,...,5,1,3.000000,0.666667,16.666667,7.666667,12.000000,6.000000,1.333333,0.000000
2026-01-24,1900-01-01 20:00:00,La Liga,Matchweek 21,Sat,Away,W,2,0,Villarreal,14,...,5,1,3.000000,0.333333,21.000000,9.333333,11.666667,6.333333,1.666667,0.000000
2026-02-01,1900-01-01 13:00:00,La Liga,Matchweek 22,Sun,Home,W,2,1,Vallecano,16,...,6,1,3.000000,0.333333,19.666667,8.000000,10.666667,6.333333,1.333333,0.000000
2026-02-08,1900-01-01 20:00:00,La Liga,Matchweek 23,Sun,Away,W,2,0,Valencia,11,...,6,1,2.000000,0.333333,18.666667,7.000000,9.333333,7.666667,1.666667,0.000000
2026-02-14,1900-01-01 20:00:00,La Liga,Matchweek 24,Sat,Home,W,4,1,Sociedad,11,...,5,1,2.000000,0.333333,13.666667,5.333333,9.666667,7.666667,1.333333,0.000000
2026-02-21,1900-01-01 17:30:00,La Liga,Matchweek 25,Sat,Away,L,1,2,Osasuna,15,...,5,0,2.666667,0.666667,12.666667,5.666667,9.666667,7.000000,1.333333,0.000000
2026-03-02,1900-01-01 20:00:00,La Liga,Matchweek 26,Mon,Home,L,0,1,Getafe,18,...,0,0,2.333333,1.000000,12.333333,5.333333,11.000000,6.333333,2.000000,0.000000
2026-03-06,1900-01-01 20:00:00,La Liga,Matchweek 27,Fri,Away,W,2,1,Celta,14,...,4,1,1.666667,1.333333,14.666667,5.666667,10.333333,7.000000,3.000000,0.333333
2026-03-14,1900-01-01 20:00:00,La Liga,Matchweek 28,Sat,Home,W,4,1,Elche,14,...,5,1,1.000000,1.333333,15.666667,5.000000,11.000000,7.666667,3.333333,0.333333
2026-03-22,1900-01-01 20:00:00,La Liga,Matchweek 29,Sun,Home,W,3,2,Ath Madrid,17,...,6,1,2.000000,1.000000,15.333333,5.333333,11.333333,7.000000,2.333333,0.333333
2026-04-04,1900-01-01 15:15:00,La Liga,Matchweek 30,Sat,Away,L,1,2,Mallorca,15,...,5,0,3.000000,1.333333,15.000000,6.333333,8.333333,5.000000,1.333333,0.333333
2026-04-10,1900-01-01 20:00:00,La Liga,Matchweek 31,Fri,Home,D,1,1,Girona,22,...,4,0,2.666667,1.666667,15.333333,7.333333,8.666667,4.333333,1.333333,0.333333
2026-04-21,1900-01-01 20:30:00,La Liga,Matchweek 32,Tue,Home,W,2,1,Alaves,24,...,1,1,1.666667,1.666667,18.000000,8.333333,8.000000,6.000000,1.666667,0.333333
2026-04-24,1900-01-01 20:00:00,La Liga,Matchweek 33,Fri,Away,D,1,1,Betis,12,...,4,0,1.333333,1.333333,20.333333,7.666667,12.000000,7.666667,1.666667,0.000000
2026-05-03,1900-01-01 20:00:00,La Liga,Matchweek 34,Sun,Away,W,2,0,Espanol,15,...,6,1,1.333333,1.000000,19.333333,8.333333,10.333333,8.333333,1.666667,0.000000
2026-05-10,1900-01-01 20:00:00,La Liga,Matchweek 35,Sun,Away,L,0,2,Barcelona,8,...,6,0,1.666667,0.666667,17.000000,7.000000,12.666667,7.000000,2.333333,0.000000
2026-05-14,1900-01-01 20:30:00,La Liga,Matchweek 36,Thu,Home,W,2,0,Oviedo,19,...,3,1,1.000000,1.000000,11.666667,4.666667,11.000000,6.666667,3.333333,0.000000
2026-05-17,1900-01-01 18:00:00,La Liga,Matchweek 37,Sun,Away,W,1,0,Sevilla,12,...,6,1,1.333333,0.666667,14.000000,4.333333,10.666667,6.000000,2.666667,0.000000
2026-05-23,1900-01-01 20:00:00,La Liga,Matchweek 38,Sat,Home,W,4,2,Ath Bilbao,13,...,5,1,1.000000,0.666667,13.000000,3.000000,9.333333,5.333333,1.333333,0.000000

In [38]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_average(x, cols=cols, new_cols=new_cols))

In [39]:
matches_rolling

                                     time     comp         round  day venue  \
team       date
Alaves     2025-09-13 1900-01-01 17:30:00  La Liga   Matchweek 4  Sat  Away
           2025-09-20 1900-01-01 17:30:00  La Liga   Matchweek 5  Sat  Home
           2025-09-24 1900-01-01 18:00:00  La Liga   Matchweek 6  Wed  Away
           2025-09-27 1900-01-01 17:30:00  La Liga   Matchweek 7  Sat  Away
           2025-10-05 1900-01-01 13:00:00  La Liga   Matchweek 8  Sun  Home
...                                   ...      ...           ...  ...   ...
Villarreal 2026-05-02 1900-01-01 13:00:00  La Liga  Matchweek 34  Sat  Home
           2026-05-10 1900-01-01 13:00:00  La Liga  Matchweek 35  Sun  Away
           2026-05-13 1900-01-01 18:00:00  La Liga  Matchweek 36  Wed  Home
           2026-05-17 1900-01-01 18:00:00  La Liga  Matchweek 37  Sun  Away
           2026-05-24 1900-01-01 20:00:00  La Liga  Matchweek 38  Sun  Home

                      result  gf  ga    opponent  sh  ...  day_code  target  \
team       date                                       ...
Alaves     2025-09-13      W   1   0  Ath Bilbao   4  ...         5       1
           2025-09-20      L   1   2     Sevilla   8  ...         5       0
           2025-09-24      D   1   1      Getafe  10  ...         2       0
           2025-09-27      L   0   1    Mallorca  12  ...         5       0
           2025-10-05      W   3   1       Elche  25  ...         6       1
...                      ...  ..  ..         ...  ..  ...       ...     ...
Villarreal 2026-05-02      W   5   1     Levante  20  ...         5       1
           2026-05-10      D   1   1    Mallorca   7  ...         6       0
           2026-05-13      L   2   3     Sevilla   6  ...         2       0
           2026-05-17      L   0   2   Vallecano  11  ...         6       0
           2026-05-24      W   5   1  Ath Madrid  14  ...         6       1

                       gf_rolling  ga_rolling  sh_rolling sot_rolling  \
team       date
Alaves     2025-09-13    1.000000    1.000000   10.333333    3.666667
           2025-09-20    0.666667    0.666667    6.666667    3.000000
           2025-09-24    1.000000    1.000000    5.666667    3.000000
           2025-09-27    1.000000    1.000000    7.333333    3.666667
           2025-10-05    0.666667    1.333333   10.000000    4.000000
...                           ...         ...         ...         ...
Villarreal 2026-05-02    1.666667    1.000000   10.666667    4.333333
           2026-05-10    2.666667    1.000000   13.333333    5.000000
           2026-05-13    2.666667    1.000000   13.333333    4.666667
           2026-05-17    2.666667    1.666667   11.000000    4.666667
           2026-05-24    1.000000    2.000000    8.000000    2.666667

                       fouls_rolling  corners_rolling  yellow_rolling  \
team       date
Alaves     2025-09-13      14.000000         4.333333        1.666667
           2025-09-20      16.000000         3.000000        2.666667
           2025-09-24      17.000000         3.666667        2.000000
           2025-09-27      20.333333         5.666667        2.333333
           2025-10-05      19.333333         6.333333        2.333333
...                              ...              ...             ...
Villarreal 2026-05-02      10.666667         3.333333        2.333333
           2026-05-10      12.666667         4.666667        2.333333
           2026-05-13      13.333333         6.000000        2.000000
           2026-05-17      12.666667         5.666667        1.666667
           2026-05-24      11.333333         6.333333        1.000000

                       red_rolling
team       date
Alaves     2025-09-13          0.0
           2025-09-20          0.0
           2025-09-24          0.0
           2025-09-27          0.0
           2025-10-05          0.0
...                            ...
Villarreal 2026-05-02          0.0
           2026-05-10          0.0
           2026-05-13          0.0
           2026-05-17          0.0
           2026-05-24          0.0

[700 rows x 29 columns]

In [40]:
matches_rolling = matches_rolling.droplevel("team")

In [41]:
matches_rolling

,time,comp,round,day,venue,result,gf,ga,opponent,sh,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,fouls_rolling,corners_rolling,yellow_rolling,red_rolling
date,,,,,,,,,,,,,,,,,,,,,
2025-09-13,1900-01-01 17:30:00,La Liga,Matchweek 4,Sat,Away,W,1,0,Ath Bilbao,4,...,5,1,1.000000,1.000000,10.333333,3.666667,14.000000,4.333333,1.666667,0.0
2025-09-20,1900-01-01 17:30:00,La Liga,Matchweek 5,Sat,Home,L,1,2,Sevilla,8,...,5,0,0.666667,0.666667,6.666667,3.000000,16.000000,3.000000,2.666667,0.0
2025-09-24,1900-01-01 18:00:00,La Liga,Matchweek 6,Wed,Away,D,1,1,Getafe,10,...,2,0,1.000000,1.000000,5.666667,3.000000,17.000000,3.666667,2.000000,0.0
2025-09-27,1900-01-01 17:30:00,La Liga,Matchweek 7,Sat,Away,L,0,1,Mallorca,12,...,5,0,1.000000,1.000000,7.333333,3.666667,20.333333,5.666667,2.333333,0.0
2025-10-05,1900-01-01 13:00:00,La Liga,Matchweek 8,Sun,Home,W,3,1,Elche,25,...,6,1,0.666667,1.333333,10.000000,4.000000,19.333333,6.333333,2.333333,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-05-02,1900-01-01 13:00:00,La Liga,Matchweek 34,Sat,Home,W,5,1,Levante,20,...,5,1,1.666667,1.000000,10.666667,4.333333,10.666667,3.333333,2.333333,0.0
2026-05-10,1900-01-01 13:00:00,La Liga,Matchweek 35,Sun,Away,D,1,1,Mallorca,7,...,6,0,2.666667,1.000000,13.333333,5.000000,12.666667,4.666667,2.333333,0.0
2026-05-13,1900-01-01 18:00:00,La Liga,Matchweek 36,Wed,Home,L,2,3,Sevilla,6,...,2,0,2.666667,1.000000,13.333333,4.666667,13.333333,6.000000,2.000000,0.0
2026-05-17,1900-01-01 18:00:00,La Liga,Matchweek 37,Sun,Away,L,0,2,Vallecano,11,...,6,0,2.666667,1.666667,11.000000,4.666667,12.666667,5.666667,1.666667,0.0
2026-05-24,1900-01-01 20:00:00,La Liga,Matchweek 38,Sun,Home,W,5,1,Ath Madrid,14,...,6,1,1.000000,2.000000,8.000000,2.666667,11.333333,6.333333,1.000000,0.0

In [42]:
matches_rolling.index = range(matches_rolling.shape[0])

In [43]:
matches_rolling

,time,comp,round,day,venue,result,gf,ga,opponent,sh,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,fouls_rolling,corners_rolling,yellow_rolling,red_rolling
0,1900-01-01 17:30:00,La Liga,Matchweek 4,Sat,Away,W,1,0,Ath Bilbao,4,...,5,1,1.000000,1.000000,10.333333,3.666667,14.000000,4.333333,1.666667,0.0
1,1900-01-01 17:30:00,La Liga,Matchweek 5,Sat,Home,L,1,2,Sevilla,8,...,5,0,0.666667,0.666667,6.666667,3.000000,16.000000,3.000000,2.666667,0.0
2,1900-01-01 18:00:00,La Liga,Matchweek 6,Wed,Away,D,1,1,Getafe,10,...,2,0,1.000000,1.000000,5.666667,3.000000,17.000000,3.666667,2.000000,0.0
3,1900-01-01 17:30:00,La Liga,Matchweek 7,Sat,Away,L,0,1,Mallorca,12,...,5,0,1.000000,1.000000,7.333333,3.666667,20.333333,5.666667,2.333333,0.0
4,1900-01-01 13:00:00,La Liga,Matchweek 8,Sun,Home,W,3,1,Elche,25,...,6,1,0.666667,1.333333,10.000000,4.000000,19.333333,6.333333,2.333333,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,1900-01-01 13:00:00,La Liga,Matchweek 34,Sat,Home,W,5,1,Levante,20,...,5,1,1.666667,1.000000,10.666667,4.333333,10.666667,3.333333,2.333333,0.0
696,1900-01-01 13:00:00,La Liga,Matchweek 35,Sun,Away,D,1,1,Mallorca,7,...,6,0,2.666667,1.000000,13.333333,5.000000,12.666667,4.666667,2.333333,0.0
697,1900-01-01 18:00:00,La Liga,Matchweek 36,Wed,Home,L,2,3,Sevilla,6,...,2,0,2.666667,1.000000,13.333333,4.666667,13.333333,6.000000,2.000000,0.0
698,1900-01-01 18:00:00,La Liga,Matchweek 37,Sun,Away,L,0,2,Vallecano,11,...,6,0,2.666667,1.666667,11.000000,4.666667,12.666667,5.666667,1.666667,0.0
699,1900-01-01 20:00:00,La Liga,Matchweek 38,Sun,Home,W,5,1,Ath Madrid,14,...,6,1,1.000000,2.000000,8.000000,2.666667,11.333333,6.333333,1.000000,0.0

In [44]:
matches_rolling

# hasta aqui

,time,comp,round,day,venue,result,gf,ga,opponent,sh,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,fouls_rolling,corners_rolling,yellow_rolling,red_rolling
0,1900-01-01 17:30:00,La Liga,Matchweek 4,Sat,Away,W,1,0,Ath Bilbao,4,...,5,1,1.000000,1.000000,10.333333,3.666667,14.000000,4.333333,1.666667,0.0
1,1900-01-01 17:30:00,La Liga,Matchweek 5,Sat,Home,L,1,2,Sevilla,8,...,5,0,0.666667,0.666667,6.666667,3.000000,16.000000,3.000000,2.666667,0.0
2,1900-01-01 18:00:00,La Liga,Matchweek 6,Wed,Away,D,1,1,Getafe,10,...,2,0,1.000000,1.000000,5.666667,3.000000,17.000000,3.666667,2.000000,0.0
3,1900-01-01 17:30:00,La Liga,Matchweek 7,Sat,Away,L,0,1,Mallorca,12,...,5,0,1.000000,1.000000,7.333333,3.666667,20.333333,5.666667,2.333333,0.0
4,1900-01-01 13:00:00,La Liga,Matchweek 8,Sun,Home,W,3,1,Elche,25,...,6,1,0.666667,1.333333,10.000000,4.000000,19.333333,6.333333,2.333333,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,1900-01-01 13:00:00,La Liga,Matchweek 34,Sat,Home,W,5,1,Levante,20,...,5,1,1.666667,1.000000,10.666667,4.333333,10.666667,3.333333,2.333333,0.0
696,1900-01-01 13:00:00,La Liga,Matchweek 35,Sun,Away,D,1,1,Mallorca,7,...,6,0,2.666667,1.000000,13.333333,5.000000,12.666667,4.666667,2.333333,0.0
697,1900-01-01 18:00:00,La Liga,Matchweek 36,Wed,Home,L,2,3,Sevilla,6,...,2,0,2.666667,1.000000,13.333333,4.666667,13.333333,6.000000,2.000000,0.0
698,1900-01-01 18:00:00,La Liga,Matchweek 37,Sun,Away,L,0,2,Vallecano,11,...,6,0,2.666667,1.666667,11.000000,4.666667,12.666667,5.666667,1.666667,0.0
699,1900-01-01 20:00:00,La Liga,Matchweek 38,Sun,Home,W,5,1,Ath Madrid,14,...,6,1,1.000000,2.000000,8.000000,2.666667,11.333333,6.333333,1.000000,0.0